CREATE TABLE addresses (
  id          INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  account_id  INT NOT NULL REFERENCES accounts(id),
  name        VARCHAR(255) NOT NULL,  -- 宛名
  postal_code VARCHAR(20) NOT NULL,   -- 郵便番号
  address     TEXT NOT NULL,          -- 住所
  phone       VARCHAR(20),            -- 電話番号
  del_flg     BOOLEAN DEFAULT FALSE,
  created_at  TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at  TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);